$(document).ready(function(){
    $("body").click(function(){
        $("body").addClass("body");
    });

    $(".card-body").click(function(){
        $(".card-body").addClass("card");
    }); 
    
    $(".card-header").click(function(){
        $(".card-header").addClass("log");
    });
    $(".ml").click(function(){
        $(".ml").addClass("mail");
    });
    $(".pw").click(function(){
        $(".pw").addClass("word");
    });
    $(".ft").click(function(){
        $(".ft").addClass("forgot");
    });
    $(".l").click(function(){
        $(".l").addClass("lob");
    });
    $(".s").click(function(){
        $(".s").addClass("siub");
    });
    $(".l").click(function(){
        $(".ll").addClass("lb");
    });
    $(".s").click(function(){
        $(".ss").addClass("sub");
    });
    $(".at").click(function(){
        $(".at").addClass("account");
    });
});